### PR TITLE
refactor!: update to bevy 0.8 and bevy_ecs_tilemap rewrite

### PR DESCRIPTION
**Pull request by Trouv**
Thanks to @nfagerlund for the help with the bevy 0.8 update and lots of troubleshooting.

There's a couple extra major changes here worth pointing out
- no more batch spawning, `bevy_ecs_tilemap` doesn't really support it in the rewrite. This will probably allow us to simplify the level spawning code, but for now it works.
- **all** tiles have `SpatialBundles` and are all children of layer entities. Before, this was only true for tiles with intgrid values and metadata. This helps with despawning levels, but it also makes the hierarchy a little less confusing. It does compromise some performance though, since potentially thousands of entities will now have components that they didn't have before.

### CODE REVIEW

**Comment by NeoRaider** [comment]
I'm currently seeing 3 issues when updating to this branch:
- When spawning the `LdtkWorldBundle` as a child of another entity (for example to apply a `Transform`) nothing is displayed at all
- When spawning the `LdtkWorldBundle` from a non-startup system (for example a state's `on_enter`), I get various error messages about missing entities, usually leading to a crash:
```
2022-08-11T21:33:44.334253Z ERROR bevy_ecs::system::commands: Failed to 'insert or spawn' bundle of type bevy_ecs_tilemap::render::extract::ExtractedTileBundle into the following invalid entities: [9v1, 7v1, 6v1, 3v1, 4v1]
2022-08-11T21:33:44.334279Z ERROR bevy_ecs::system::commands: Failed to 'insert or spawn' bundle of type bevy_ecs_tilemap::render::extract::ExtractedTilemapBundle into the following invalid entities: [10v1, 8v1]
2022-08-11T21:33:44.334289Z ERROR bevy_ecs::system::commands: Failed to 'insert or spawn' bundle of type bevy_ecs_tilemap::render::extract::ExtractedTilemapTextureBundle into the following invalid entities: [10v1, 8v1]
thread 'Compute Task Pool (3)' panicked at 'called `Result::unwrap()` on an `Err` value: NoSuchEntity(8v1)', /home/neoraider/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs_tilemap-0.7.0/src/render/prepare.rs:82:55
```

- When applying a scaling factor to the camera's `OrthographicProjection`, I'm seeing weird rendering issues at tile edges that weren't there with Bevy 0.7 (here shown with a file based on one of LDtk's example levels and a 4x scaling):

Before:
before
After:
after

**Comment by Trouv** [comment]
Thanks for testing it out @NeoRaider !
> When spawning the LdtkWorldBundle as a child of another entity (for example to apply a Transform) nothing is displayed at all

I'm not able to reproduce this. Does your parent entity have a `SpatialBundle`? It needs one.

> When spawning the LdtkWorldBundle from a non-startup system (for example a state's on_enter), I get various error messages about missing entities, usually leading to a crash

Seems to be the same issue as #107. Using `bevy_ecs_tilemap` on its own this way works perfectly fine so it's definitely an issue with `bevy_ecs_ldtk`. I'm guessing it has something to do with scheduling ambiguity between the two plugins. I'll look into it now.

> When applying a scaling factor to the camera's OrthographicProjection, I'm seeing weird rendering issues at tile edges that weren't there with Bevy 0.7 (here shown with a file based on one of LDtk's example levels and a 4x scaling)

I'm also not able to reproduce this. Using the same example from LDtk, I'm changing the `OrthographicProjection::scale` and nothing's wrong on my end?

**Comment by NeoRaider** [comment]
> Thanks for testing it out @NeoRaider !
> 
> > When spawning the LdtkWorldBundle as a child of another entity (for example to apply a Transform) nothing is displayed at all
> 
> I'm not able to reproduce this. Does your parent entity have a `SpatialBundle`? It needs one.

Thanks, that was the issue - I was only adding `Transform`/`GlobalTransform` instead of the whole bundle.

> 
> > When spawning the LdtkWorldBundle from a non-startup system (for example a state's on_enter), I get various error messages about missing entities, usually leading to a crash
> 
> Seems to be the same issue as #107. Using `bevy_ecs_tilemap` on its own this way works perfectly fine so it's definitely an issue with `bevy_ecs_ldtk`. I'm guessing it has something to do with scheduling ambiguity between the two plugins. I'll look into it now.
> 
> > When applying a scaling factor to the camera's OrthographicProjection, I'm seeing weird rendering issues at tile edges that weren't there with Bevy 0.7 (here shown with a file based on one of LDtk's example levels and a 4x scaling)
> 
> I'm also not able to reproduce this. Using the same example from LDtk, I'm changing the `OrthographicProjection::scale` and nothing's wrong on my end?

I'll try to reduce my code to a minimal reproducer.

**Comment by Trouv** [comment]
Closes #91 
Closes #107

**Comment by Trouv** [comment]
There seems to be a similar issue w/ hot reloading

**Comment by NeoRaider** [comment]
My rendering issue turned out to be https://github.com/bevyengine/bevy/issues/5266. Inserting `.insert_resource(ImageSettings::default_nearest())` before `DefaultPlugins` fixed it.

**Comment by Trouv** [comment]
I've promoted the Hot reloading bug to its own issue, so I'm going to merge this PR. I'll make another PR for that fix when it's ready

**Pull request merged**
